from enum import Enum


class Error(Enum):
    SETTINGS_LOADING = "Settings could not be loaded!"
    SETTINGS_KEY_NOT_EXIST = "Settings key does not exists!"
    STYLES_LOADING = "Styles could not be loaded!"
    LANG_TRANSLATION_MISSING = "Translation missing!"
    LANG_KEY_NOT_EXIST = "Translation key does not exist!"
    LANG_INVALID_SIZE = "Length of translation file is different than default lang file!"
    LANG_NOT_EXIST = "Language does not exist!"
    STYLE_LOADING = "Not allowed to  override default theme ('blue', 'dark-blue', 'green'). Chose different file name"
    STYLE_NOT_EXIST = "Style does not exist!"
    KEYBINDINGS_LOADING = "Keybindings could not be loaded!"
    INVALID_PROJECT_FILE = "Project file is invalid!"
    CREATE_PROJECT = "Could not create project file!"
    UNSUPPORTED_IMAGE_SHAPE = "Unsupported image shape / layout"
    CONVOLUTION_NEGATIVE_STRIDE = "Negative Stride"
    CONVOLUTION_KERNAL_DIMENSION = "Only 2D kernal supported"
    CONVOLUTION_KERNAL_DIMENSION_EVEN = "Only odd kernal dimensions"
    CONVOLUTION_KERNAL_DATA_TYPE = "Kernel weight must be float or None"
    CONVOLUTION_IMAGE_DATA_TYPE = "Only support dtype: uint8 or float32"
    VERSION_GIT_VERSION = "Could not get buildid. Maybe not Git installed. Or you use compiled version."
    COMBOBOXEXTENDED_BIND_RESIZE = "Could not bind on resize"
    COMBOBOXEXTENDED_REMOVE_SCROLLBAR = "Could not remove scrollbar"
    COMBOBOXEXTENDED_RESIZE = "Could not resize"
    COMBOBOXEXTENDED_CLEAR_LIST = "Could not clear list"
    DETAILSFRAME_SET_MASTER = "Wrong master set"
    RESIZE_IMAGE_COMPLEX = "Complex images not supported"
    RESIZE_IMAGE_NON_FINITE = "NaN / Inf not supported"
    RESIZE_IMAGE_SCALE = "Image is not scaled or clipped in range [0,255]."
    RESIZE_IMAGE_UNKNOWN_DTYPE = "Unsupported dtype of image"
    RESIZE_IMAGE_NONE = "Image is None"
    RESIZE_IMAGE_CHANNEL = "Channel number is not 3 or 4."
    RESIZE_IMAGE_NDIM = "NDIM is not 2 or 3."
    SAVE_IMAGE = "Could not save image"
    EXPECTED_NDARRAY = "Expected ndarrady"
    SAVE_PROJECT = "Could not save project"
    DRAW_KEYPOINT = "Wrong draw style"
    UNKNOWN_FEATURE = "Unknown Feature"
    IMAGE_NOT_NUMBER = "Image doesnt contain numbers"
    XFEATURES2D = "Operation is not available in your OpenCV build. OpenCV must be built with OPENCV_ENABLE_NONFREE and xfeatures2d."


class Info(Enum):
    PRELOADING_CONFIG = "Preloading config library"
    PRELOADING_LANG = "Preloading lang library"
    PRELOADING_STYLE = "Preloading style library"
    PRELOADING_KEYBINDING = "Preloading keybinding library"
    PRELOADING_PROJECT = "Preloading project library"
    BUILDING_MAIN = "Building Main window"
    INIT_DONE = "Init Done!"
    CLOSE_WINDOW = "Window closed"
    RETURN_EMPTY_IMAGE = "Returning empty image"
    FORMAT_NESTED_RECURSIVE_REFERENCE = "↻ Recursive reference"
    FORMAT_NESTED_MAX_DEPTH = " ... [Line depth reached]"
    FORMAT_NESTED_TRUNCATED = " ... [Truncated]"
